apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: er5e3wh7b-python-gitops
  description: This is GitOps manifest for er5e3wh7b-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=er5e3wh7b-python
    backstage.io/kubernetes-id: er5e3wh7b-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: er5e3wh7b-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:er5e3wh7b-python
