apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: er5e3wh7b-python
  janus-idp.io/tekton: er5e3wh7b-python
  backstage.io/kubernetes-id: er5e3wh7b-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: er5e3wh7b-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
