apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: er5e3wh7b-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: er5e3wh7b-python 
  name: er5e3wh7b-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: er5e3wh7b-python
    weight: 100 
