apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: er5e3wh7b-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: er5e3wh7b-python 
  name: er5e3wh7b-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: er5e3wh7b-python 
